In [29]:
import numpy as np

In [30]:
np.random.seed(42)

n_samples = 1000
n_features = 3

covariance = np.array([
    [1.0, 0.7, 0.5],
    [0.7, 1.0, 0.3],
    [0.5, 0.3, 1.0]
])

mean = np.zeros(n_features)
X = np.random.multivariate_normal(mean, covariance, n_samples)

X = X * 10 + 50

In [31]:
np.cov(X, rowvar=False)


array([[ 92.43365358,  64.07696156,  47.6093483 ],
       [ 64.07696156,  92.496381  ,  28.33709437],
       [ 47.6093483 ,  28.33709437, 103.49023688]])

In [32]:
X_Tilde = X - np.mean(X, axis=0)
m = X_Tilde.T @ X_Tilde / (999)
m

array([[ 92.43365358,  64.07696156,  47.6093483 ],
       [ 64.07696156,  92.496381  ,  28.33709437],
       [ 47.6093483 ,  28.33709437, 103.49023688]])

In [36]:
eigenvalues, eigenvectors = np.linalg.eig(m)
eigenvalues, eigenvectors

eigenvalues = eigenvalues / np.sum(eigenvalues)
eigenvalues

pca_values = X_Tilde @ eigenvectors
pca_values

array([[ -6.2918686 ,  -3.15257375,  -0.73122857],
       [-20.93496767,   1.21257656,  -0.9825662 ],
       [-21.34020418,   2.66411732,   7.50961371],
       ...,
       [ -7.74387333,   1.28237063,   0.99245191],
       [ 14.33096068,  -0.94224563,   0.05735223],
       [ 18.52712268,   1.26593394,   1.97432361]], shape=(1000, 3))