In [12]:
import tkinter as tk
from tkinter import filedialog, messagebox
import pandas as pd
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_squared_error, r2_score
from scipy.stats import ttest_ind
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
import numpy as np
import seaborn as sns
from sklearn import preprocessing
from sklearn.svm import SVC

xve = ''
yve = 'click'
fpv = 'ad_click_dataset.csv'
#imports data
origData = pd.read_csv(fpv)
df = origData
#displays first 5 rows
print(df.head())
#checks for missing values
print(df.isnull().any())

#fills missing values
df.fillna(df.mean(numeric_only=True).round(1), inplace=True)
string_columns = df.select_dtypes(include=['object']).columns
df[string_columns] = df[string_columns].fillna(df[string_columns].mode().iloc[0])
#print(df.isnull().any())
#changes categorical values to numbers
le = preprocessing.LabelEncoder()
for column_name in df.columns:
    if df[column_name].dtype == object:
        df[column_name] = le.fit_transform(df[column_name])
else:
    pass
#scales and normalizes data
scaler = StandardScaler()
ndf = scaler.fit_transform(df)
normalized_df = pd.DataFrame(ndf, columns=df.columns)
print("Raw Data")
print(df.head())
print("\nNormalized Data")
print(normalized_df.head())

#more preprocessing
abc = df.columns.get_loc(yve)
test2 = []
test3 = []
for i in range(len(df.columns)):
    if(i != abc):
        test2.append(i)
limit = 5
for i in range(len(test2)):
    if(i<limit):
        test3.append(df.columns[test2[i]])

X = df[test3]
y = df[yve]
X.to_numpy()
y.to_numpy()


     id full_name   age      gender device_type ad_position browsing_history  \
0   670   User670  22.0         NaN     Desktop         Top         Shopping   
1  3044  User3044   NaN        Male     Desktop         Top              NaN   
2  5912  User5912  41.0  Non-Binary         NaN        Side        Education   
3  5418  User5418  34.0        Male         NaN         NaN    Entertainment   
4  9452  User9452  39.0  Non-Binary         NaN         NaN     Social Media   

  time_of_day  click  
0   Afternoon      1  
1         NaN      1  
2       Night      1  
3     Evening      1  
4     Morning      0  
id                  False
full_name           False
age                  True
gender               True
device_type          True
ad_position          True
browsing_history     True
time_of_day          True
click               False
dtype: bool
Raw Data
     id  full_name   age  gender  device_type  ad_position  browsing_history  \
0   670       2531  22.0       0            0 

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [13]:
#80/20 train test split with random seed
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#first model
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_pred = log_reg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
#printing scores/evaulation
print(f'Accuracy: {accuracy}')
print(f'F1: {f1}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print('Classification Report:')
print(classification_report(y_test, y_pred))

#second model
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred)
recall_rf = recall_score(y_test, y_pred)
#printing scores/evaulation
print(f'Accuracy (Random Forest): {accuracy_rf}')
print(f'F1 (Random Forest): {f1_rf}')
print(f'Precision (Random Forest): {precision_rf}')
print(f'Recall (Random Forest): {recall_rf}')
print('Classification Report (Random Forest):')
print(classification_report(y_test, y_pred_rf))


Accuracy: 0.6505
F1: 0.7872146118721461
Precision: 0.6497487437185929
Recall: 0.9984555984555985
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.01      0.02       705
           1       0.65      1.00      0.79      1295

    accuracy                           0.65      2000
   macro avg       0.72      0.50      0.40      2000
weighted avg       0.70      0.65      0.52      2000



c:\Users\enson\OneDrive\Desktop\NewBeginnings\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy (Random Forest): 0.8875
F1 (Random Forest): 0.9173705471905986
Precision: 0.6497487437185929
Recall: 0.9984555984555985
Classification Report (Random Forest):
              precision    recall  f1-score   support

           0       0.92      0.75      0.82       705
           1       0.87      0.96      0.92      1295

    accuracy                           0.89      2000
   macro avg       0.90      0.86      0.87      2000
weighted avg       0.89      0.89      0.88      2000



In [18]:
#k fold implementation


(array([   0,    1,    2, ..., 9997, 9998, 9999]),
 array([4000, 4001, 4002, ..., 5997, 5998, 5999]))